#!/bin/bash

#CUDA_VISIBLE_DEVICES=2 python learnt_prototypical_contrastive_main.py --operation Train --dataset River --dataset_path /mnt/DADOS_PONTOISE_1/keiller/datasets/rios/ --training_images no so --testing_images se --crop_size 128 --stride_crop 64 --batch_size 8 --output_path river/crop_128_dws_m1/ --model WideResNet --margin 1 --miner True --weight_sampler True --crop True --dynamic_sampler True --epoch 500 > river/crop_128_dws_m1/out.txt
#
#CUDA_VISIBLE_DEVICES=2 python learnt_prototypical_contrastive_main.py --operation Train --dataset River --dataset_path /mnt/DADOS_PONTOISE_1/keiller/datasets/rios/ --training_images no so --testing_images se --crop_size 128 --stride_crop 64 --batch_size 8 --output_path river/crop_128_dws_m2/ --model WideResNet --margin 2 --miner True --weight_sampler True --crop True --dynamic_sampler True --epoch 500 > river/crop_128_dws_m2/out.txt

CUDA_VISIBLE_DEVICES=0 python learnt_prototypical_contrastive_main.py --operation Train --dataset River --dataset_path /mnt/DADOS_PARIS_1/keiller/datasets/rios/ --training_images no so --testing_images se --crop_size 128 --stride_crop 64 --batch_size 8 --output_path river/crop_128_dws_m3/ --model WideResNet --margin 3 --miner True --weight_sampler True --crop True --dynamic_sampler True --epoch 500 > river/crop_128_dws_m3/out.txt

CUDA_VISIBLE_DEVICES=0 python learnt_prototypical_contrastive_main.py --operation Train --dataset River --dataset_path /mnt/DADOS_PARIS_1/keiller/datasets/rios/ --training_images no so --testing_images se --crop_size 128 --stride_crop 64 --batch_size 8 --output_path river/crop_128_dws_m4/ --model WideResNet --margin 4 --miner True --weight_sampler True --crop True --dynamic_sampler True --epoch 500 > river/crop_128_dws_m4/out.txt

CUDA_VISIBLE_DEVICES=0 python learnt_prototypical_contrastive_main.py --operation Train --dataset River --dataset_path /mnt/DADOS_PARIS_1/keiller/datasets/rios/ --training_images no so --testing_images se --crop_size 128 --stride_crop 64 --batch_size 8 --output_path river/crop_128_dws_m5/ --model WideResNet --margin 5 --miner True --weight_sampler True --crop True --dynamic_sampler True --epoch 500 > river/crop_128_dws_m5/out.txt

CUDA_VISIBLE_DEVICES=0 python learnt_prototypical_contrastive_main.py --operation Train --dataset River --dataset_path /mnt/DADOS_PARIS_1/keiller/datasets/rios/ --training_images no so --testing_images se --crop_size 128 --stride_crop 64 --batch_size 8 --output_path river/crop_128_dws_m6/ --model WideResNet --margin 6 --miner True --weight_sampler True --crop True --dynamic_sampler True --epoch 500 > river/crop_128_dws_m6/out.txt

CUDA_VISIBLE_DEVICES=0 python learnt_prototypical_contrastive_main.py --operation Train --dataset River --dataset_path /mnt/DADOS_PARIS_1/keiller/datasets/rios/ --training_images no so --testing_images se --crop_size 128 --stride_crop 64 --batch_size 8 --output_path river/crop_128_dws_m7/ --model WideResNet --margin 7 --miner True --weight_sampler True --crop True --dynamic_sampler True --epoch 500 > river/crop_128_dws_m7/out.txt

CUDA_VISIBLE_DEVICES=0 python learnt_prototypical_contrastive_main.py --operation Train --dataset River --dataset_path /mnt/DADOS_PARIS_1/keiller/datasets/rios/ --training_images no so --testing_images se --crop_size 128 --stride_crop 64 --batch_size 8 --output_path river/crop_128_dws_m8/ --model WideResNet --margin 8 --miner True --weight_sampler True --crop True --dynamic_sampler True --epoch 500 > river/crop_128_dws_m8/out.txt

CUDA_VISIBLE_DEVICES=0 python learnt_prototypical_contrastive_main.py --operation Train --dataset River --dataset_path /mnt/DADOS_PARIS_1/keiller/datasets/rios/ --training_images no so --testing_images se --crop_size 128 --stride_crop 64 --batch_size 8 --output_path river/crop_128_dws_m9/ --model WideResNet --margin 9 --miner True --weight_sampler True --crop True --dynamic_sampler True --epoch 500 > river/crop_128_dws_m9/out.txt

CUDA_VISIBLE_DEVICES=0 python learnt_prototypical_contrastive_main.py --operation Train --dataset River --dataset_path /mnt/DADOS_PARIS_1/keiller/datasets/rios/ --training_images no so --testing_images se --crop_size 128 --stride_crop 64 --batch_size 8 --output_path river/crop_128_dws_m10/ --model WideResNet --margin 10 --miner True --weight_sampler True --crop True --dynamic_sampler True --epoch 500 > river/crop_128_dws_m10/out.txt

CUDA_VISIBLE_DEVICES=0 python learnt_prototypical_contrastive_main.py --operation Train --dataset River --dataset_path /mnt/DADOS_PARIS_1/keiller/datasets/rios/ --training_images no so --testing_images se --crop_size 128 --stride_crop 64 --batch_size 8 --output_path river/crop_128_dws_nominer_m3/ --model WideResNet --margin 3 --miner False --weight_sampler True --crop True --dynamic_sampler True --epoch 500 > river/crop_128_dws_nominer_m3/out.txt
